# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

tasks:
  run:
    desc: Runs a given solution with the provided name and part
    cmds:
      - cabal exec Codyssi -- {{.CLI_ARGS}}

  build:
    desc: Builds the project
    cmds:
      - cabal build

  create-solution:
    desc: Creates a new solution with the given name
    cmds:
      - touch $(echo "data/{{.CLI_ARGS}}.txt" | awk '{print tolower($0)}')
      - NAME={{.CLI_ARGS}} envsubst < Solution.hs.tmpl > lib/{{.CLI_ARGS}}.hs
      - sed -i '/exposed-modules:/a\    {{.CLI_ARGS}}' Codyssi.cabal
